/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testErc20TokenSol from "./TestErc20Token.sol";
export type { testErc20TokenSol };
export type { PeerLocal } from "./PeerLocal";
export type { ReputationToken } from "./ReputationToken";
