import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from 'next/router'
import { ConnectWallet } from "../../features/ConnectWallet";
import { Layout } from "../../features/Layout";
import Link from "next/link";
import { useCommunity, useCommunityIPFS } from "src/features/peerlocal/hooks/usePeerLocal";
import { usePeerLocalContract } from "src/features/peerlocal/hooks/usePeerLocalContract";


const Welcome: NextPage = () => {
    const router = useRouter()
    const c = useCommunity({ id: router.query.welcome_id ? router.query.welcome_id.toString() : "0" })
    const ci = useCommunityIPFS({ ipfsHash: c.data?.community?.ipfsMetadata })
    const sig = router.query.signature ? router.query.signature?.toString() : ""
    const { joinCommunity } = usePeerLocalContract();
    const joinHandler = async (e) => {
        e.preventDefault();
        joinCommunity.mutateAsync({
            communityId: router.query.welcome_id ? router.query.welcome_id.toString() : "",
            ownerSignature: sig
        })
    }

    return (
        <>
            <Head>
                <title>Welcome Personal Page</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Welcome to our <span className="text-accent">{ci.data?.Name}</span>, DAO;
                        Please sign the message to join our community
                    </h1>
                    <button className="btn mw-50 btn-accent" onClick={joinHandler}>Join</button>
                </div>
            </Layout>
        </>
    );
};

export default Welcome;