/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testErc20TokenSol from "./TestErc20Token.sol";
export { PeerLocal__factory } from "./PeerLocal__factory";
export { ReputationToken__factory } from "./ReputationToken__factory";
