import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../features/Layout";
import Link from "next/link";

const CreateListing: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create a listing...</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
            <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <p className="text-2xl font-extrabold tracking-tight text-white">
                        Create a Listing using the form below...
                    </p>
                </div>
            </Layout>
        </div>
    )
}

export default CreateListing