import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../features/Layout";
import Link from "next/link";

const Market: NextPage = () => {
    const listings = [
        {
            "name": "name1",
            "price": 1250.00,
            "availability": true,
            "img": "https://placeholder.pics/svg/300"
        },
        {
            "name": "name2",
            "price": 3450.00,
            "availability": true,
            "img": "https://placeholder.pics/svg/300"
        },
        {
            "name": "name3",
            "price": 11250.00,
            "availability": false,
            "img": "https://placeholder.pics/svg/300"
        },
        {
            "name": "name4",
            "price": 1269.00,
            "availability": true,
            "img": "https://placeholder.pics/svg/300"
        },
        {
            "name": "name5",
            "price": 14295.00,
            "availability": true,
            "img": "https://placeholder.pics/svg/300"
        },
        {
            "name": "name6",
            "price": 420.69,
            "availability": true,
            "img": "https://placeholder.pics/svg/300"
        },
        {
            "name": "name7",
            "price": 1337.00,
            "availability": true,
            "img": "https://placeholder.pics/svg/300"
        }
    ]
    return (
        <div>
            <Head>
                <title>Market Overview</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Welcome to our <span className="text-accent">Market</span>
                    </h1>
                    <p className="text-2xl font-extrabold tracking-tight text-white">
                        You can <Link href="/createListing" className="text-accent underline">List an item</Link>
                    </p>
                    <p className="text-2xl font-extrabold tracking-tight text-white">
                        Or Browse active listings below:
                    </p>
                </div>
            </Layout>
        </div>
    )
}

export default Market