import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "../features/Layout";
import Link from "next/link";

const Market: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Market Overview</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
            <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Welcome to our <span className="text-accent">Market</span>
                    </h1>
                    <p className="text-2xl font-extrabold tracking-tight text-white">
                        You can <Link href="/createListing" className="text-accent underline">List an item</Link>
                    </p>
                    <p className="text-2xl font-extrabold tracking-tight text-white">
                        Or Browse active listings below:
                    </p>
                </div>
            </Layout>
        </div>
    )
}

export default Market